### ISSUE TITLE
Unable to undo BlockFile tweaks

### ISSUE THREAD

**Issue by Alex9001** [DavidXanatos/priv10#1] opened 2018-12-27 04:13 UTC
Under search & cortana if searchui.exe is disabled it cannot be re-enabled (Switched to off). Same with smartscreen, and I assume all blockfile tweaks.

I am running .exe in admin mode.

Win 10 x64 v1809

Please inform how to manually undo blockfile tweak.

**Comment by DavidXanatos** [comment] 2018-12-28 08:08
To manually unblock the file you go to the files location, open the file properties, go to the advanced security options and look for a "deny rule" with special permissions, when you click on the rule it should deny "Execution", delete that rule and the file should be unblocked.

I will look into it and try to fix it asap, the tool should be able to undoing any tweak

**Comment by DavidXanatos** [comment] 2019-01-03 19:56
I tried the file blocking unblocking on the Calculator.exe and it works as it should, possibly after a fail windows does not restart the cortana prozess proeprly, try rebooting. 
I'll close the issue for now as i cant reproduce it

**Closed as completed by DavidXanatos** 2019-01-03 19:56 UTC

**Comment by CapitanPlanet** [comment] 2019-01-04 09:40
Had the same problem... in this file noone had any permissions. I added "users" group and give read and execute permission. It worked! Win 10 x64 Polish ver

**Comment by LBdN** [comment] 2019-01-17 21:15
same here. but the fix above doesnt work.

**Comment by LBdN** [comment] 2019-01-17 22:16
but the deny rule was there.

**Comment by Muchoburrito** [comment] 2019-04-01 22:19
the above does work perfectly fine thanks for the fix DavidXanatos i was getting frustrated lmao 

here is what i did follow along Properties on SearchUi file> Security > Advanced > Change permissions> double click on every option there in the permission entries that are listed till one of them says deny on the drop down and switch it to allow.  all the other should say allow unless you have changed them.
